// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-steputils/v2/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewRestorer creates a new instance of Restorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Restorer {
	mock := &Restorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Restorer is an autogenerated mock type for the Restorer type
type Restorer struct {
	mock.Mock
}

type Restorer_Expecter struct {
	mock *mock.Mock
}

func (_m *Restorer) EXPECT() *Restorer_Expecter {
	return &Restorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type Restorer
func (_mock *Restorer) Restore(input cache.RestoreCacheInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cache.RestoreCacheInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Restorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type Restorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - input cache.RestoreCacheInput
func (_e *Restorer_Expecter) Restore(input interface{}) *Restorer_Restore_Call {
	return &Restorer_Restore_Call{Call: _e.mock.On("Restore", input)}
}

func (_c *Restorer_Restore_Call) Run(run func(input cache.RestoreCacheInput)) *Restorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cache.RestoreCacheInput
		if args[0] != nil {
			arg0 = args[0].(cache.RestoreCacheInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Restorer_Restore_Call) Return(err error) *Restorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Restorer_Restore_Call) RunAndReturn(run func(input cache.RestoreCacheInput) error) *Restorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}
