// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-steputils/v2/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewSaver creates a new instance of Saver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Saver {
	mock := &Saver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Saver is an autogenerated mock type for the Saver type
type Saver struct {
	mock.Mock
}

type Saver_Expecter struct {
	mock *mock.Mock
}

func (_m *Saver) EXPECT() *Saver_Expecter {
	return &Saver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type Saver
func (_mock *Saver) Save(input cache.SaveCacheInput) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cache.SaveCacheInput) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Saver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Saver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - input cache.SaveCacheInput
func (_e *Saver_Expecter) Save(input interface{}) *Saver_Save_Call {
	return &Saver_Save_Call{Call: _e.mock.On("Save", input)}
}

func (_c *Saver_Save_Call) Run(run func(input cache.SaveCacheInput)) *Saver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cache.SaveCacheInput
		if args[0] != nil {
			arg0 = args[0].(cache.SaveCacheInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Saver_Save_Call) Return(err error) *Saver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Saver_Save_Call) RunAndReturn(run func(input cache.SaveCacheInput) error) *Saver_Save_Call {
	_c.Call.Return(run)
	return _c
}
