// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package compression

import (
	"sync"
)

// Ensure, that ArchiveDependencyCheckerMock does implement ArchiveDependencyChecker.
// If this is not the case, regenerate this file with moq.
var _ ArchiveDependencyChecker = &ArchiveDependencyCheckerMock{}

// ArchiveDependencyCheckerMock is a mock implementation of ArchiveDependencyChecker.
//
//	func TestSomethingThatUsesArchiveDependencyChecker(t *testing.T) {
//
//		// make and configure a mocked ArchiveDependencyChecker
//		mockedArchiveDependencyChecker := &ArchiveDependencyCheckerMock{
//			CheckDependenciesFunc: func() bool {
//				panic("mock out the CheckDependencies method")
//			},
//		}
//
//		// use mockedArchiveDependencyChecker in code that requires ArchiveDependencyChecker
//		// and then make assertions.
//
//	}
type ArchiveDependencyCheckerMock struct {
	// CheckDependenciesFunc mocks the CheckDependencies method.
	CheckDependenciesFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// CheckDependencies holds details about calls to the CheckDependencies method.
		CheckDependencies []struct {
		}
	}
	lockCheckDependencies sync.RWMutex
}

// CheckDependencies calls CheckDependenciesFunc.
func (mock *ArchiveDependencyCheckerMock) CheckDependencies() bool {
	callInfo := struct {
	}{}
	mock.lockCheckDependencies.Lock()
	mock.calls.CheckDependencies = append(mock.calls.CheckDependencies, callInfo)
	mock.lockCheckDependencies.Unlock()
	if mock.CheckDependenciesFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.CheckDependenciesFunc()
}

// CheckDependenciesCalls gets all the calls that were made to CheckDependencies.
// Check the length with:
//
//	len(mockedArchiveDependencyChecker.CheckDependenciesCalls())
func (mock *ArchiveDependencyCheckerMock) CheckDependenciesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckDependencies.RLock()
	calls = mock.calls.CheckDependencies
	mock.lockCheckDependencies.RUnlock()
	return calls
}
