// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-utils/v2/env"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Format provides a mock function for the type Manager
func (_mock *Manager) Format(keys []string) string {
	ret := _mock.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for Format")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]string) string); ok {
		r0 = returnFunc(keys)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Manager_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type Manager_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
//   - keys []string
func (_e *Manager_Expecter) Format(keys interface{}) *Manager_Format_Call {
	return &Manager_Format_Call{Call: _e.mock.On("Format", keys)}
}

func (_c *Manager_Format_Call) Run(run func(keys []string)) *Manager_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Format_Call) Return(s string) *Manager_Format_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Manager_Format_Call) RunAndReturn(run func(keys []string) string) *Manager_Format_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type Manager
func (_mock *Manager) Load(envRepository env.Repository) []string {
	ret := _mock.Called(envRepository)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(env.Repository) []string); ok {
		r0 = returnFunc(envRepository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// Manager_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Manager_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - envRepository env.Repository
func (_e *Manager_Expecter) Load(envRepository interface{}) *Manager_Load_Call {
	return &Manager_Load_Call{Call: _e.mock.On("Load", envRepository)}
}

func (_c *Manager_Load_Call) Run(run func(envRepository env.Repository)) *Manager_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 env.Repository
		if args[0] != nil {
			arg0 = args[0].(env.Repository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Load_Call) Return(strings []string) *Manager_Load_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *Manager_Load_Call) RunAndReturn(run func(envRepository env.Repository) []string) *Manager_Load_Call {
	_c.Call.Return(run)
	return _c
}
