// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnvGetter is an autogenerated mock type for the EnvGetter type
type EnvGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *EnvGetter) Get(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
