// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-steputils/v2/ruby"
	mock "github.com/stretchr/testify/mock"
)

// NewEnvironment creates a new instance of Environment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvironment(t interface {
	mock.TestingT
	Cleanup(func())
}) *Environment {
	mock := &Environment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Environment is an autogenerated mock type for the Environment type
type Environment struct {
	mock.Mock
}

type Environment_Expecter struct {
	mock *mock.Mock
}

func (_m *Environment) EXPECT() *Environment_Expecter {
	return &Environment_Expecter{mock: &_m.Mock}
}

// IsGemInstalled provides a mock function for the type Environment
func (_mock *Environment) IsGemInstalled(gem string, version string) (bool, error) {
	ret := _mock.Called(gem, version)

	if len(ret) == 0 {
		panic("no return value specified for IsGemInstalled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(gem, version)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(gem, version)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(gem, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Environment_IsGemInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGemInstalled'
type Environment_IsGemInstalled_Call struct {
	*mock.Call
}

// IsGemInstalled is a helper method to define mock.On call
//   - gem string
//   - version string
func (_e *Environment_Expecter) IsGemInstalled(gem interface{}, version interface{}) *Environment_IsGemInstalled_Call {
	return &Environment_IsGemInstalled_Call{Call: _e.mock.On("IsGemInstalled", gem, version)}
}

func (_c *Environment_IsGemInstalled_Call) Run(run func(gem string, version string)) *Environment_IsGemInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Environment_IsGemInstalled_Call) Return(b bool, err error) *Environment_IsGemInstalled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Environment_IsGemInstalled_Call) RunAndReturn(run func(gem string, version string) (bool, error)) *Environment_IsGemInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// IsSpecifiedASDFRubyInstalled provides a mock function for the type Environment
func (_mock *Environment) IsSpecifiedASDFRubyInstalled(workdir string) (bool, string, error) {
	ret := _mock.Called(workdir)

	if len(ret) == 0 {
		panic("no return value specified for IsSpecifiedASDFRubyInstalled")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return returnFunc(workdir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(workdir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(workdir)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(workdir)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Environment_IsSpecifiedASDFRubyInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSpecifiedASDFRubyInstalled'
type Environment_IsSpecifiedASDFRubyInstalled_Call struct {
	*mock.Call
}

// IsSpecifiedASDFRubyInstalled is a helper method to define mock.On call
//   - workdir string
func (_e *Environment_Expecter) IsSpecifiedASDFRubyInstalled(workdir interface{}) *Environment_IsSpecifiedASDFRubyInstalled_Call {
	return &Environment_IsSpecifiedASDFRubyInstalled_Call{Call: _e.mock.On("IsSpecifiedASDFRubyInstalled", workdir)}
}

func (_c *Environment_IsSpecifiedASDFRubyInstalled_Call) Run(run func(workdir string)) *Environment_IsSpecifiedASDFRubyInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Environment_IsSpecifiedASDFRubyInstalled_Call) Return(b bool, s string, err error) *Environment_IsSpecifiedASDFRubyInstalled_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *Environment_IsSpecifiedASDFRubyInstalled_Call) RunAndReturn(run func(workdir string) (bool, string, error)) *Environment_IsSpecifiedASDFRubyInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// IsSpecifiedRbenvRubyInstalled provides a mock function for the type Environment
func (_mock *Environment) IsSpecifiedRbenvRubyInstalled(workdir string) (bool, string, error) {
	ret := _mock.Called(workdir)

	if len(ret) == 0 {
		panic("no return value specified for IsSpecifiedRbenvRubyInstalled")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return returnFunc(workdir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(workdir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(workdir)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(workdir)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Environment_IsSpecifiedRbenvRubyInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSpecifiedRbenvRubyInstalled'
type Environment_IsSpecifiedRbenvRubyInstalled_Call struct {
	*mock.Call
}

// IsSpecifiedRbenvRubyInstalled is a helper method to define mock.On call
//   - workdir string
func (_e *Environment_Expecter) IsSpecifiedRbenvRubyInstalled(workdir interface{}) *Environment_IsSpecifiedRbenvRubyInstalled_Call {
	return &Environment_IsSpecifiedRbenvRubyInstalled_Call{Call: _e.mock.On("IsSpecifiedRbenvRubyInstalled", workdir)}
}

func (_c *Environment_IsSpecifiedRbenvRubyInstalled_Call) Run(run func(workdir string)) *Environment_IsSpecifiedRbenvRubyInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Environment_IsSpecifiedRbenvRubyInstalled_Call) Return(b bool, s string, err error) *Environment_IsSpecifiedRbenvRubyInstalled_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *Environment_IsSpecifiedRbenvRubyInstalled_Call) RunAndReturn(run func(workdir string) (bool, string, error)) *Environment_IsSpecifiedRbenvRubyInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// RubyInstallType provides a mock function for the type Environment
func (_mock *Environment) RubyInstallType() ruby.InstallType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RubyInstallType")
	}

	var r0 ruby.InstallType
	if returnFunc, ok := ret.Get(0).(func() ruby.InstallType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ruby.InstallType)
	}
	return r0
}

// Environment_RubyInstallType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RubyInstallType'
type Environment_RubyInstallType_Call struct {
	*mock.Call
}

// RubyInstallType is a helper method to define mock.On call
func (_e *Environment_Expecter) RubyInstallType() *Environment_RubyInstallType_Call {
	return &Environment_RubyInstallType_Call{Call: _e.mock.On("RubyInstallType")}
}

func (_c *Environment_RubyInstallType_Call) Run(run func()) *Environment_RubyInstallType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Environment_RubyInstallType_Call) Return(installType ruby.InstallType) *Environment_RubyInstallType_Call {
	_c.Call.Return(installType)
	return _c
}

func (_c *Environment_RubyInstallType_Call) RunAndReturn(run func() ruby.InstallType) *Environment_RubyInstallType_Call {
	_c.Call.Return(run)
	return _c
}
