// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewFileProvider creates a new instance of FileProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileProvider {
	mock := &FileProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileProvider is an autogenerated mock type for the FileProvider type
type FileProvider struct {
	mock.Mock
}

type FileProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FileProvider) EXPECT() *FileProvider_Expecter {
	return &FileProvider_Expecter{mock: &_m.Mock}
}

// Contents provides a mock function for the type FileProvider
func (_mock *FileProvider) Contents(ctx context.Context, srcPath string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, srcPath)

	if len(ret) == 0 {
		panic("no return value specified for Contents")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, srcPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, srcPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, srcPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileProvider_Contents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Contents'
type FileProvider_Contents_Call struct {
	*mock.Call
}

// Contents is a helper method to define mock.On call
//   - ctx context.Context
//   - srcPath string
func (_e *FileProvider_Expecter) Contents(ctx interface{}, srcPath interface{}) *FileProvider_Contents_Call {
	return &FileProvider_Contents_Call{Call: _e.mock.On("Contents", ctx, srcPath)}
}

func (_c *FileProvider_Contents_Call) Run(run func(ctx context.Context, srcPath string)) *FileProvider_Contents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_Contents_Call) Return(readCloser io.ReadCloser, err error) *FileProvider_Contents_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *FileProvider_Contents_Call) RunAndReturn(run func(ctx context.Context, srcPath string) (io.ReadCloser, error)) *FileProvider_Contents_Call {
	_c.Call.Return(run)
	return _c
}

// LocalPath provides a mock function for the type FileProvider
func (_mock *FileProvider) LocalPath(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for LocalPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileProvider_LocalPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalPath'
type FileProvider_LocalPath_Call struct {
	*mock.Call
}

// LocalPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *FileProvider_Expecter) LocalPath(ctx interface{}, path interface{}) *FileProvider_LocalPath_Call {
	return &FileProvider_LocalPath_Call{Call: _e.mock.On("LocalPath", ctx, path)}
}

func (_c *FileProvider_LocalPath_Call) Run(run func(ctx context.Context, path string)) *FileProvider_LocalPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_LocalPath_Call) Return(s string, err error) *FileProvider_LocalPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *FileProvider_LocalPath_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *FileProvider_LocalPath_Call {
	_c.Call.Return(run)
	return _c
}
