// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewInputParser creates a new instance of InputParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInputParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *InputParser {
	mock := &InputParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InputParser is an autogenerated mock type for the InputParser type
type InputParser struct {
	mock.Mock
}

type InputParser_Expecter struct {
	mock *mock.Mock
}

func (_m *InputParser) EXPECT() *InputParser_Expecter {
	return &InputParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type InputParser
func (_mock *InputParser) Parse(input interface{}) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InputParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type InputParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - input interface{}
func (_e *InputParser_Expecter) Parse(input interface{}) *InputParser_Parse_Call {
	return &InputParser_Parse_Call{Call: _e.mock.On("Parse", input)}
}

func (_c *InputParser_Parse_Call) Run(run func(input interface{})) *InputParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *InputParser_Parse_Call) Return(err error) *InputParser_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InputParser_Parse_Call) RunAndReturn(run func(input interface{}) error) *InputParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
