// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewArchiveDependencyChecker creates a new instance of ArchiveDependencyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArchiveDependencyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArchiveDependencyChecker {
	mock := &ArchiveDependencyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ArchiveDependencyChecker is an autogenerated mock type for the ArchiveDependencyChecker type
type ArchiveDependencyChecker struct {
	mock.Mock
}

type ArchiveDependencyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *ArchiveDependencyChecker) EXPECT() *ArchiveDependencyChecker_Expecter {
	return &ArchiveDependencyChecker_Expecter{mock: &_m.Mock}
}

// CheckDependencies provides a mock function for the type ArchiveDependencyChecker
func (_mock *ArchiveDependencyChecker) CheckDependencies() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckDependencies")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ArchiveDependencyChecker_CheckDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDependencies'
type ArchiveDependencyChecker_CheckDependencies_Call struct {
	*mock.Call
}

// CheckDependencies is a helper method to define mock.On call
func (_e *ArchiveDependencyChecker_Expecter) CheckDependencies() *ArchiveDependencyChecker_CheckDependencies_Call {
	return &ArchiveDependencyChecker_CheckDependencies_Call{Call: _e.mock.On("CheckDependencies")}
}

func (_c *ArchiveDependencyChecker_CheckDependencies_Call) Run(run func()) *ArchiveDependencyChecker_CheckDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ArchiveDependencyChecker_CheckDependencies_Call) Return(b bool) *ArchiveDependencyChecker_CheckDependencies_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ArchiveDependencyChecker_CheckDependencies_Call) RunAndReturn(run func() bool) *ArchiveDependencyChecker_CheckDependencies_Call {
	_c.Call.Return(run)
	return _c
}
