// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	analytics "github.com/bitrise-io/go-utils/v2/analytics"
	mock "github.com/stretchr/testify/mock"
)

// TrackerFactory is an autogenerated mock type for the TrackerFactory type
type TrackerFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *TrackerFactory) Execute(_a0 ...analytics.Properties) analytics.Tracker {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 analytics.Tracker
	if rf, ok := ret.Get(0).(func(...analytics.Properties) analytics.Tracker); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analytics.Tracker)
		}
	}

	return r0
}
